@WebAPIAutores_HostAddress = http://localhost:5142
@id = 1

GET {{WebAPIAutores_HostAddress}}/api/libros/{{id}}
Accept: application/json

###

@id = 1
@titulo = "Libro ABC"

POST {{WebAPIAutores_HostAddress}}/api/libros
Content-Type: application/json

{
    "titulo": {{titulo}},
    "autorId": {{id}}
}